import React from 'react';
import { LandingHeader } from '../components/LandingHeader';
import { Lock } from 'lucide-react';

export const Privacy = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <LandingHeader />
      
      <main className="pt-24 pb-16">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-12">
            <div className="flex justify-center mb-4">
              <div className="p-3 bg-purple-100 dark:bg-purple-900 rounded-lg">
                <Lock className="w-8 h-8 text-purple-500 dark:text-purple-400" />
              </div>
            </div>
            <h1 className="text-4xl font-bold text-gray-900 dark:text-white">Privacy Policy</h1>
            <p className="mt-4 text-lg text-gray-600 dark:text-gray-300">
              Last updated: March 9, 2025
            </p>
          </div>

          <div className="prose prose-lg dark:prose-invert max-w-none">
            <p>
              This Privacy Policy explains our policies regarding the collection, use, and disclosure of your information when you use NinjaText, located at https://ninjatext.app. By using our service, you agree to the collection and use of information according to this policy.
            </p>

            <h2>Interpretation and Definitions</h2>
            <h3>Definitions</h3>
            <ul>
              <li><strong>Account</strong>: A unique account created for you to access our service or parts of our service.</li>
              <li><strong>Company</strong>: [Your Company Name], doing business as NinjaText, located in Victoria, British Columbia, Canada.</li>
              <li><strong>Device</strong>: Any device that can access the service such as a computer, cellphone, or digital tablet.</li>
              <li><strong>Personal Data</strong>: Information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong>: Refers to the website and any related services operated by NinjaText.</li>
              <li><strong>Usage Data</strong>: Data collected automatically, either generated by the use of the service or from the service infrastructure itself.</li>
            </ul>

            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>
              We may ask you to provide us with certain personally identifiable information, including but not limited to your email address, when you register for an account or sign up via Google. This data is used to contact or identify you and manage your account.
            </p>

            <h4>Usage Data</h4>
            <p>
              Usage Data is collected automatically when using the service. This may include information such as your device's Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our service that you visit, and other diagnostic data.
            </p>

            <h4>Tracking Technologies and Cookies</h4>
            <p>
              Our service does not use cookies or similar tracking technologies to track your activities. We do not store any cookies on your device.
            </p>

            <h2>Use of Your Personal Data</h2>
            <p>
              NinjaText may use your personal data for the following purposes:
            </p>
            <ul>
              <li>To provide and maintain our service, including monitoring usage.</li>
              <li>To manage your account as a user of the service.</li>
              <li>To contact you regarding updates or informative communications about the service.</li>
              <li>To manage your requests, inquiries, or support needs.</li>
              <li>To perform internal data analysis for service improvement and user experience enhancement.</li>
            </ul>

            <h2>Retention of Your Personal Data</h2>
            <p>
              We retain your personal data only for as long as necessary for the purposes outlined in this Privacy Policy, unless a longer retention period is required by law for legal, security, or other legitimate business reasons.
            </p>

            <h2>Transfer of Your Personal Data</h2>
            <p>
              Your information may be transferred and maintained on computers located outside of your governmental jurisdiction, where data protection laws may differ. By using our service, you consent to the transfer of information, including personal data, to Canada and any location where we operate.
            </p>

            <h2>Delete Your Personal Data</h2>
            <p>
              You may request deletion of your personal data through your account settings or by contacting us directly. Note that certain information may be retained as required by law or for legitimate business purposes.
            </p>

            <h2>Security of Your Personal Data</h2>
            <p>
              We take reasonable measures to protect your personal data, though no method of transmission over the Internet is completely secure.
            </p>

            <h2>Children's Privacy</h2>
            <p>
              Our service is not intended for individuals under the age of 18. We do not knowingly collect data from anyone under this age. If you become aware that a user under the age of 18 has provided us with personal data, please contact us immediately.
            </p>

            <h2>Links to Other Websites</h2>
            <p>
              Our service may include links to other websites not operated by us. We are not responsible for the content, privacy policies, or practices of third-party sites.
            </p>

            <h2>Changes to This Privacy Policy</h2>
            <p>
              We may update this policy from time to time. We will notify you of changes by posting the new policy on this page and updating the "Last updated" date.
            </p>

            <h2>Contact Us</h2>
            <p>
              For questions about this Privacy Policy, please contact us at support@ninjatext.app.
            </p>
          </div>
        </div>
      </main>
    </div>
  );
};